name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Dar permisos a Maven Wrapper
        run: chmod +x ./mvnw

      - name: Compilar proyecto
        run: ./mvnw compile --no-transfer-progress

      - name: Ejecutar tests
        run: ./mvnw verify --no-transfer-progress

      - name: Publicar reporte de tests
        uses: ctrf-io/github-test-reporter@v1
        if: always()
        with:
         report-path: './target/*-reports/*.xml'
         github-report: true
         integrations-config: |
           {
             "junit-to-ctrf": {
               "enabled": true,
               "action": "convert",
               "options": {
                 "output": "./ctrf-reports/ctrf-report.json",
                 "toolname": "junit-to-ctrf"
               }
             }
           }
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generar badges de cobertura
        uses: cicirello/jacoco-badge-generator@v2
        if: always()
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          badges-directory: .github/badges
          generate-branches-badge: true
          generate-summary: true